{"name": "test_with_issue_link", "status": "passed", "start": 1648187316041, "stop": 1648187316041, "uuid": "1822d5b7-cdfe-43d2-a5ef-b1b4b036ef06", "historyId": "8e69671c30e6f24682aca2c3362c2b5f", "testCaseId": "aa2048cc93855d34d56f6e308344fb3b", "fullName": "test_pytest.test_link#test_with_issue_link", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_link"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "1692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_link"}], "links": [{"type": "issue", "url": "140", "name": "Pytest-flaky test retries shows like test steps"}]}