{"name": "test_eval[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 is None", "trace": "yy = 3\n\n    @pytest.mark.parametrize(\"yy\", [3, 4, None])\n    def test_eval(yy):\n>       assert yy is None\nE       assert 3 is None\n\ntest_expectation.py:11: AssertionError"}, "parameters": [{"name": "yy", "value": "3"}], "start": 1647920834258, "stop": 1647920834258, "uuid": "e5303a5b-4920-49ac-8e07-f496cdd643be", "historyId": "5a4479dd8974b2baaa3c8cdbde7b42ba", "testCaseId": "ff6166714df71c7f259a948c6e62680c", "fullName": "test_pytest.test_expectation#test_eval", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_expectation"}, {"name": "host", "value": "IT-L-YANGYL"}, {"name": "thread", "value": "16588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_expectation"}]}