{"uuid": "6e0d371a-a414-405d-bf5a-1e2f50017844", "children": ["f47ccc2a-b003-456f-bbc2-847c333e19df"], "befores": [{"name": "_xunit_setup_method_fixture_TestFrame", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\n", "trace": "  File \"C:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\python.py\", line 893, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\python.py\", line 778, in _call_with_optional_argument\n    func()\n  File \"E:\\PycharmProject\\test_pytest\\test_base.py\", line 11, in setup\n    self.driver = webdriver.Firefox()\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 164, in __init__\n    self.service.start()\n  File \"C:\\Users\\yilin.yang\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1649228866936, "stop": 1649228866945}], "start": 1649228866936, "stop": 1649228867077}